# Generated by Django 4.2.4 on 2023-09-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetvalue',
            name='asset',
        ),
        migrations.AddField(
            model_name='asset',
            name='values',
            field=models.ManyToManyField(to='portfolio.assetvalue'),
        ),
    ]
