# Generated by Django 4.2.4 on 2023-09-04 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_asset_values_asset_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='values',
        ),
        migrations.AddField(
            model_name='assetvalue',
            name='asset',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio.asset'),
        ),
    ]
