# Generated by Django 4.2.4 on 2023-10-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_asset_values_assetvalue_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='max_drawdown',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='retur',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='risk',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
